[project]
name = "6-pretrain-finetune"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.0.1",
    "bitsandbytes==0.45.3",
    "transformers>=4.43,<4.46",
    "accelerate>=0.33,<0.36",
    "peft>=0.11.1",
    "optimum>=1.20.0",
    "sentencepiece",
    "ipywidgets",
    "datasets",
    "traitlets",
    "tqdm",
    "rich",
]
